[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.0"
serde = "1.0.152"
serde_json = "1.0.93"
serde_derive = "1.0.152"
diesel = { version = "2.0.3", features = ["sqlite"] }
dotenv = "0.15.0"
uuid = { version = "1.3.0", features = ["serde", "v4"]}